apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000       # puerto expuesto en el cluster
      targetPort: 5000 # puerto dentro del contenedor
  type: ClusterIP      # solo accesible dentro del cluster



# type: NodePort → abre un puerto de tu máquina hacia los pods.
# port: 80 → puerto del service (interno en cluster).
# targetPort: 3000 → puerto real del contenedor.
# nodePort: 30080 → puerto en tu PC para acceder (puede ser entre 30000–32767).